export const SORT_TYPES = [
  { label: 'Price: Low to High', value: 'price_low_to_high' },
  { label: 'Price: High to Low', value: 'price_high_to_low' },
  { label: 'Recently listed', value: 'recently_listed' },
  { label: 'Recently sold', value: 'recently_sold' },
];

export const ORDER_TYPES = [{ label: 'Buy Now', value: 'buy_now' }];

export const MOONSAMA_MAX_SUPPLY = 1000;

export const MOONSAMA_TRAITS = {
  Neon: 6,
  'Yellow Bird': 120,
  'Rainbow Shirt': 141,
  'No body accessory': 863,
  'Blue Hair': 37,
  'Bored Eyes': 213,
  'No hand accessory': 939,
  'No dimension': 994,
  'Purple Bird': 70,
  'Red Shirt': 157,
  'Aviator Hat': 13,
  'Yellow Geeky Glasses': 106,
  'Blue Bird': 153,
  'Green Shirt': 194,
  'Straight green': 41,
  'Black Geeky Glasses': 99,
  'Pink Bird': 117,
  'Blue Shirt': 176,
  'Happy Eyes': 238,
  'Cyan Bird': 152,
  'Orange Bufoon': 33,
  'Red Mohawk': 49,
  Cyclops: 34,
  'Green Bird': 127,
  Cigar: 128,
  'Blue Bufoon': 26,
  'No jacket': 137,
  'Blonde Hair': 36,
  'White Shades': 32,
  'Red Bird': 124,
  'Astronaut Helmet': 9,
  'Curious Eyes': 254,
  'Judo Outfit': 93,
  'Straight Red': 43,
  'Green Mohawk': 46,
  'No hat': 69,
  'Green Bufoon': 29,
  'Golden Bird': 19,
  'Sheriff Outfit': 80,
  'Black Cap': 39,
  'Black Bird': 55,
  'Samurai Top': 39,
  'Orange Cap': 45,
  'Grey Headset': 36,
  'Blue Mohawk': 45,
  'Black Mohawk': 59,
  'Blonde Mohawk': 42,
  'Blue Cap': 36,
  'Cheerleader Pom': 20,
  'Brown Cowboy': 23,
  'Detective Cap': 38,
  'Red Headset': 10,
  'Straight Black': 45,
  'Champion Gloves': 15,
  'White Bird': 63,
  'Straight Blonde': 38,
  'Black Shades': 24,
  'Hero Outfit': 22,
  'Pink Headset': 11,
  'Black Cowboy': 24,
  'Green Hair': 30,
  'Green Headset': 7,
  'Moonfinity Gauntlet': 9,
  'Boxing Gloves': 17,
  'Gold Chain': 9,
  Crown: 2,
};

export const PONDSAMA_NATURE_TRAITS = {
  Calm: 1,
  Pacific: 2,
  Lazy: 3,
  Rude: 4,
  Reckless: 5,
  Stubborn: 6,
  Solid: 7,
  Tough: 8,
  Robust: 9,
  Impatient: 10,
  Shy: 11,
  Swift: 12,
};

export const PONDSAMA_PASSIVE_TRAITS = {
  'Erratic Mimicry': 13,
  'Acquired Taste': 14,
  'Reckless Response': 15,
  Necromancy: 16,
  'Adrenaline Rush': 17,
  'Misery Loves Company': 18,
  'Trust Issues': 19,
  'Dressed for the Occasion': 20,
  Berserk: 21,
  'Slow Learner': 22,
  'Trophy Collector': 23,
  Seafury: 24,
  'Thrill of the Hunt': 25,
  Finslinger: 26,
  'Unstoppable Force': 27,
  'Bubble Time': 28,
  'Conditional Altruism': 29,
  'Pass the Baton': 29,
  'Kind Spirit': 29,
  'Mourning Routine': 29,
  'Hippocratic Oath': 29,
  'Unscrupulous Gourmet': 29,
  Gluttony: 29,
  'Heroic Stance': 29,
  'Hardening Scales': 29,
  Masochism: 29,
};

export const PONDSAMA_SkILL_TRAITS = {
  'Entropic Wave': 29,
  'Jack of All Trades': 29,
  'Lottery Day': 29,
  Maelstrom: 29,
  'Second Chances': 29,
  'Sharpen Up': 29,
  Streamline: 29,
  'Thieving Ways': 29,
  'Blind Rage': 29,
  Cannibalism: 29,
  'Eyes on the Prey': 29,
  'Grim Reaper': 29,
  'Expansive Wave': 29,
  'Long Shot': 29,
  'Pick on the Weak': 29,
  'Piling Up': 29,
  'Puncture Shot': 29,
  'Shuri-scale': 29,
  'Sunken Beam': 29,
  'The Bigger They Are...': 29,
  'Abyssal Shock': 29,
  'Back to the Pool': 29,
  'Blooming Waters': 29,
  'Healing Wave': 29,
  Paranoia: 29,
  'Reality Check': 29,
  'Selfless Sacrifice': 29,
  'Sunken Curse': 29,
  'Survival of the Luckiest': 29,
  'Timely Aid': 29,
  'Absolute Vortex': 29,
  'Bad Blood': 29,
  'Deep Slumber': 29,
  Headbutt: 29,
  'Rhino Slam': 29,
  'Scale Up': 29,
  'Soul Bond': 29,
  'Sunken Shield': 29,
  'Terrifying Stare': 29,
  'Thorn Suit': 29,
};
