import { Theme } from '@mui/material';

export const styles = (theme: Theme) => ({
  placeholderContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    padding: 20,
    margin: '20 0',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    justifyItems: 'center',
    marginTop: -30,
    textAlign: 'center',
    minHeight: '800px',
    position: 'absolute ',
    marginLeft: 'auto',
    marginRight: 'auto',
    left: 0,
    right: 0,
  },
  backVideo: {
    position: 'absolute',
    zIndex: "-10"
  },
  contentPaper: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: '800px',
    justifyContent: 'center',
    padding: "100px 200px",
    position: 'absolute ',
    marginLeft: 'auto',
    marginRight: 'auto',
    left: 0,
    right: 0,
  },
  logo: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    height: 'auto',
    '& > img': {
      maxWidth: '100%',
      marginBottom: '-5px',
    },
    [theme.breakpoints.down('sm')]: {
      //marginLeft: '20px',
    },
    "@media (max-width : 1910px)": {
      // width : 80,
    }
  },
  navItem: {
    margin: '0 8%',
    textDecoration: 'none !important',
    flexShrink: 0,
    fontSize: "20px",
    color: "#FFF",
  },

  mainTitle: {
    borderRadius: 0,
    fontFamily: 'Poppins',
    fontSize: '80px',
    fontWeight: '900',
    lineHeight: '120px',
    letterSpacing: '0em',
    textAlign: 'center',
    color: '#FFFFFF',
    alignItems: 'center',
    flex: 'none',
    flexGrow: 0,
  },
  subText: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: '24px',
    lineHeight: '36px',
    alignItems: 'center',
    textAlign: 'center',
    color: '#FFFFFF',
    textTransform: 'uppercase',
  },
  centerGrid: {
    position: 'absolute',
    left: '50%',
    transform: "translate(-50%, 300%)",
    order: 1
  },

  subButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '20px 40px',
    width: '344px',
    height: '76px',
    background: '#F5E2B3',
    borderRadius: '20px',
    flex: 'none',
    flexGrow: 0,
  },
  subQuiz: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '24px',
    lineHeight: '36px',
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#01472A',
    flex: 'none',
    flexGrow: 0,
  },
  videoTitle: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: '40px',
    lineHeight: '60px',
    alignItems: 'center',
    textAlign: 'center',
    color: '#FFFFFF',
    flex: 'none',
    flexGrow: 0,
    marginBottom: "50px",
  },
  boardTitlePaper: {
    background: 'rgba(0, 206, 76, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '60px',
    width: '470px',
    maxHeight: '176px',
    borderRadius: '10px',
  },
  boardTitle: {
    width: '173px',
    height: '36px',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '24px',
    lineHeight: '36px',
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#00CE4C',
    margin: "10px",
  },
  boardBody: {
    width: '390px',
    height: '60px',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: '40px',
    lineHeight: '60px',
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: ' #FFFFFF',
  },
  boardSubTitle: {
    width: '439px',
    height: '36px',
    fontFamily: 'Poppins',
    fonSttyle: 'normal',
    fontWeight: '900',
    fontSize: '24px',
    lineHeight: '36px',
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#FFFFFF',
  },
  boardSubBody: {
    width: '456px',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    alignItems: 'center',
    color: '#FFFFFF',
  },
  boardButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '20px 40px',
    background: 'rgba(0, 206, 76, 0.6)',
    borderRadius: '20px',
    width: '230px',
    height: '64px',
    marginTop: '20px'
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '15px',
    lineHeight: '24px',
  }

});