
name: Buddies-web
on: 
  push:
    branches:
      - main
  workflow_dispatch:   
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.Buddeis_Host }}
          username: ${{ secrets.Buddeis_UserName }}
          password: ${{ secrets.Buddeis_Password }}
          port: "22"
          script: |
            cd /home/buddies/Buddies-web
            git checkout main
            git fetch
            git pull
            pm2 stop buddies
            rm -rf build
            yarn build
            cd build
            pm2 restart buddies
